name: "Docker"

on:
    push:
        paths-ignore:
            - "**.md"
            - "**.json"
        branches:
            - "main"

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: "read"
  packages: "write"

jobs:
  push:
    runs-on: "ubuntu-latest"
    
    steps:
      - name: "GitHub: Checkout Repository"
        uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683" # v4.2.2

      - name: "GitHub: Setup Nix"
        uses: "custom-workflows/setup-nix@d3dc49dd7bd37d10de81c938bebefad918e4d499" # latest
        with:
          install_url: "https://releases.nixos.org/nix/nix-2.29.0/install"
          extra_nix_config: |
              extra-experimental-features = nix-command flakes

      - name: "Nix: Build and Push"
        shell: "bash"
        run: |
          nix run .#docker:push
        env:
          OCI_REGISTRY: "ghcr.io"
          OCI_REGISTRY_REPOSITORY: "${{ github.repository }}"
          OCI_REGISTRY_USERNAME: ${{ github.repository_owner }}
          OCI_REGISTRY_PASSWORD: ${{ github.token }}